[id]
name = agentsight
version = 0.1.0

[package]
id = agentsight
check_for_updates = false

[install]
is_configured = 0
state = enabled

[ui]
is_visible = 1
label = AgentSight

[launcher]
author = AgentSight
description = Observability for MCP clients and autonomous agents accessing Splunk
version = 0.1.0

[triggers]
reload.indexes = simple
reload.props = simple
reload.transforms = simple
reload.savedsearches = simple
reload.commands = simple
